import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";

import SessionProvider from "@/components/auth/Provider";

import prisma from "@/lib/prisma";
import { getUser } from "@/utils/get-user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionUser = await getUser();
  if (!sessionUser) {
    redirect("/signin");
  }
  const user = sessionUser
    ? await prisma.user.findUnique({
        where: { id: sessionUser?.id },
      })
    : null;

  if (user?.role == "PLATFORM_ADMIN") {
    redirect("/dashboard");
  }

  if (user?.role == "SHOP_ADMIN") {
    redirect("/coffee-shop");
  }

  const coffeeShops = sessionUser
    ? await prisma.coffeeShop.findMany({
        where: { adminId: sessionUser?.id },
      })
    : [];

  if (!coffeeShops || coffeeShops.length === 0) {
    return <div>You don&apos;t have any coffee shops</div>;
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider sessionUser={sessionUser} userRole={user?.role}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
